# Using PostgresSQL for all environments
# gem install pg
# Ensuring that the PostgresSQL 10 gem is defined in the Gemfile
# gem 'pg'
development:
  adapter: postgresql
  database: sbcuervos
  username: postgres
  password: a123123a
  pool: 5
  timeout: 5000

# Warning: The database defined as "tests" will be erased and re-generated
# from your development database when you run "rake".
# Do not set this db to the same as development or production
test:
  adapter: postgresql
  database: sbcuervos
  username: postgres
  password: a123123a
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sbcuervos
  username: postgres
  password: a123123a
  pool: 5
  timeout: 5000